server:
  port: ${PORT:8080}

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: ${OKTA_ISSUER_URI}
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}